# Generated by Django 4.0.2 on 2022-05-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='seller',
            new_name='is_owner',
        ),
    ]
