# Generated by Django 4.0.2 on 2022-05-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_alter_customuser_is_active_and_more'),
        ('owners', '0003_alter_customuser_is_superuser'),
    ]

    operations = [
    ]
