# Generated by Django 4.0.2 on 2022-05-10 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Countryside', 'Countryside'), ('Apartments', 'Apartments')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('rooms', models.IntegerField()),
                ('garage', models.BooleanField()),
                ('bathrooms', models.IntegerField()),
                ('m2', models.IntegerField()),
                ('rent_or_sell', models.CharField(choices=[('rent', 'Rent'), ('buy', 'Buy')], default='buy', max_length=4)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.city')),
            ],
        ),
    ]
