# Generated by Django 4.0.2 on 2022-05-19 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/house_pictures')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='houses.house')),
            ],
        ),
    ]
