# Generated by Django 4.0.2 on 2022-05-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_housepictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housepictures',
            name='file',
            field=models.ImageField(upload_to='house_pictures'),
        ),
    ]
