# Generated by Django 4.0.2 on 2022-06-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_like_alter_house_likes_alter_housepictures_house'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
