# Generated by Django 4.0.2 on 2022-11-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
