# Generated by Django 4.0.2 on 2022-11-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0011_rename_theshold_price_threshold_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=38.96667, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=-0.18333, max_digits=12),
            preserve_default=False,
        ),
    ]
