# Generated by Django 4.0.2 on 2022-11-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0012_house_latitude_house_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='house',
            name='title',
            field=models.CharField(default='titulo default', max_length=100),
            preserve_default=False,
        ),
    ]
