# Generated by Django 4.0.2 on 2022-11-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0014_city_latitude_city_longitude_alter_house_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Countryside', 'Countryside'), ('Apartments', 'Apartments')], default='Residential', max_length=11),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
