# Generated by Django 4.1.5 on 2023-01-19 02:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0015_alter_house_type_delete_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housepictures",
            name="file",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
