# Generated by Django 4.1.5 on 2023-01-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0017_alter_city_latitude_alter_city_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name="city",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name="house",
            name="latitude",
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name="house",
            name="longitude",
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
    ]
